# Generated by Django 2.2.6 on 2019-10-23 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='titel',
            new_name='title',
        ),
    ]
